import { useState, useEffect } from 'react';
import { Loader, Card, FormField } from '../components';
import { api } from '../constants';

const RenderCards = ({ data, title }) => {
    return (
        data?.length > 0 
            ? data.map((post) => 
                <Card key={post._id} 
                    id={post._id} 
                    name={post.name} 
                    prompt={post.prompt} 
                    image={post.image} />
                ) 
            : <h2 className='mt-5 font-bold text-blue text-xl uppercase'>{title}</h2>
    );
};

const Home = () => {
    const [posts, setPosts] = useState([]);
    const [loading, setLoading] = useState(false);
    const [searchText, setSearchText] = useState("");
    const [searchedResults, setSearchedResults] = useState([]);
    const [searchTimeout, setSearchTimeout] = useState(null);

    useEffect(() => {
        const fetchPosts = async () => {
            setLoading(true);

            try {
                const response = await api.get('/api/v1/get_posts');

                setPosts(response.data.posts);
            } catch (error) {
                console.log(error);
            } finally {
                setLoading(false);
            }
        };

        fetchPosts();
    }, []);

    const handleSearchChange = (e) => {
        clearTimeout(searchTimeout);
        setSearchText(e.target.value);

        setSearchTimeout(
            setTimeout(() => {
                const filteredPosts = posts.filter((post) => 
                    post.name.toLowerCase().includes(searchText.toLowerCase()) ||
                    post.prompt.toLowerCase().includes(searchText.toLowerCase()));
    
                setSearchedResults(filteredPosts);
            }, 500)
        );
    }

    return (
        <section className='max-w-7xl mx-auto'>
            <div>
                <h1 className='font-extrabold text-dark-gray text-[32px]'>
                    The Community Showcase
                </h1>
                <p className='mt-2 text-[#666e75] text-md max-w-[512px]'>
                    Browse through a collection of imaginative and visually stunning images 
                    generated by DALL-E AI
                </p>
            </div>

            <div className='mt-16'>
                <FormField
                    LabelName='Search posts'
                    type='text'
                    name='text'
                    placeholder='Search for a prompt or creator'
                    value={searchText}
                    handleChange={handleSearchChange}
                />
            </div>

            <div className='mt-10'>
                {
                    loading ? (
                        <div className='flex justify-center items-center'>
                            <Loader />
                        </div>
                    ) : (
                        <>
                            {
                                searchText && (
                                    <h2 className='font-medium text-gray text-xl mb-3'>
                                        Showing results for <span className='text-dark-gray'>{searchText}</span>
                                    </h2>
                                )
                            }
                            <div className="grid lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2 grid-cols-1 gap-3">
                                {
                                    searchText ? (
                                        <RenderCards 
                                            data={searchedResults}
                                            title='No search results found'
                                        />
                                    ) : (
                                        <RenderCards 
                                            data={posts}
                                            title='No posts found'
                                        />
                                    )
                                }
                            </div>
                        </>
                    )
                }
            </div>
        </section>
    );
}

export default Home;